### ISSUE TITLE
@UseGuards(AuthGuard('local')) 无效问题

### ISSUE THREAD

**Issue by Jsmond2016** [Walker-Leee/nest-starter#19]
作者你好，通过你的 B 站视频，跟到 jwt 这一小节知识的时候，发现 我得不到和你一样的效果；创建用户始终都是报 401 没有权限。只有去掉 @UseGuards(AuthGuard('local'))  装饰器才能正常返回 token；

我下载了你的代码本地跑起来，发现也是一样的问题。@UseGuards(AuthGuard('local'))  这个装饰器没有正确 【跳过鉴权】

查看了文档，这种用法在[nest官方文档](https://docs.nestjs.com/security/authentication)中确实是可以的；

![image](https://user-images.githubusercontent.com/25282180/134791347-2502b4c9-4fd9-4c6b-9a30-8e0c52d3a3ba.png)

但是不知道具体为什么没有出现预期效果？

作者大大有空可以帮助看一下吗？万分感谢~~~

我的 nest 仓库地址：https://github.com/Jsmond2016/nest-demo

**Comment by Jsmond2016** [comment]
> 作者你好，通过你的 B 站视频，跟到 jwt 这一小节知识的时候，发现 我得不到和你一样的效果；创建用户始终都是报 401 没有权限。只有去掉 @UseGuards(AuthGuard('local')) 装饰器才能正常返回 token；
> 
> 我下载了你的代码本地跑起来，发现也是一样的问题。@UseGuards(AuthGuard('local')) 这个装饰器没有正确 【跳过鉴权】
> 
> 查看了文档，这种用法在[nest官方文档](https://docs.nestjs.com/security/authentication)中确实是可以的；
> 
> ![image](https://user-images.githubusercontent.com/25282180/134791347-2502b4c9-4fd9-4c6b-9a30-8e0c52d3a3ba.png)
> 
> 但是不知道具体为什么没有出现预期效果？
> 
> 作者大大有空可以帮助看一下吗？万分感谢~~~
> 
> 我的 nest 仓库地址：https://github.com/Jsmond2016/nest-demo

诶，找到解决办法了，我的问题~~

**Comment by Holl9** [comment]
Nice
